NDefines.NGame.START_DATE = "2052.1.1.12"
NDefines.NGame.END_DATE = "2080.1.1.12"

NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_STATE_R = 255
NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_STATE_G = 255
NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_STATE_B = 255
NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_R = 1.58
NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_G = 0.5
NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_B = 0.5